---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gmsalm-demo
  name: gmsalm-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmsalm-demo
  template:
    metadata:
      labels:
        app: gmsalm-demo
    spec:
      securityContext:
        windowsOptions:
          gmsaCredentialSpecName: credspec
      containers:
      - name: iis
        image: <your image>
        imagePullPolicy: IfNotPresent
        command:
          - powershell
        args:
          - -File
          - /gmsa-demo/run.ps1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - wspool
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gmsalm-demo
  name: gmsalm-demo
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: gmsalm-demo
  type: LoadBalancer